# Generated by Django 6.0.6 on 2026-08-04 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('connection.received', 'Lời làm quen mới'), ('connection.accepted', 'Kết nối được chấp nhận'), ('connection.declined', 'Lời làm quen bị từ chối'), ('message.received', 'Tin nhắn mới'), ('call.missed', 'Cuộc gọi nhỡ'), ('verification.submitted', 'Đã gửi xác minh'), ('verification.needs_more_info', 'Cần bổ sung xác minh'), ('verification.approved', 'Xác minh thành công'), ('verification.rejected', 'Xác minh bị từ chối'), ('account.warning', 'Cảnh báo tài khoản')], db_index=True, max_length=64)),
                ('entity_type', models.CharField(blank=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='notificatio_user_id_554261_idx')],
            },
        ),
    ]
