# Generated by Django 6.0.6 on 2026-08-04 05:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OccupationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DiscoveryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveSmallIntegerField(default=18)),
                ('max_age', models.PositiveSmallIntegerField(default=99)),
                ('min_height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('province_codes', models.JSONField(blank=True, default=list)),
                ('hometown_codes', models.JSONField(blank=True, default=list)),
                ('occupation_ids', models.JSONField(blank=True, default=list)),
                ('education_levels', models.JSONField(blank=True, default=list)),
                ('income_bands', models.JSONField(blank=True, default=list)),
                ('relationship_goals', models.JSONField(blank=True, default=list)),
                ('verified_only', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('birth_date', models.DateField(db_index=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('non_binary', 'Phi nhị nguyên'), ('other', 'Khác')], db_index=True, max_length=24)),
                ('interested_genders', models.JSONField(blank=True, default=list)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(230)])),
                ('occupation_text', models.CharField(blank=True, max_length=160)),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'THPT'), ('college', 'Cao đẳng'), ('university', 'Đại học'), ('postgraduate', 'Sau đại học'), ('other', 'Khác')], db_index=True, max_length=32)),
                ('income_band', models.CharField(blank=True, choices=[('under_10', 'Dưới 10 triệu'), ('10_20', '10–20 triệu'), ('20_30', '20–30 triệu'), ('30_50', '30–50 triệu'), ('50_100', '50–100 triệu'), ('above_100', 'Trên 100 triệu'), ('private', 'Không muốn công khai')], db_index=True, max_length=24)),
                ('relationship_status', models.CharField(blank=True, choices=[('single', 'Độc thân'), ('divorced', 'Đã ly hôn'), ('widowed', 'Góa')], max_length=24)),
                ('relationship_goal', models.CharField(blank=True, choices=[('friendship', 'Làm quen'), ('serious', 'Tìm hiểu nghiêm túc'), ('long_term', 'Hẹn hò lâu dài'), ('marriage', 'Hướng tới kết hôn')], db_index=True, max_length=24)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('smoking_status', models.CharField(blank=True, choices=[('never', 'Không'), ('sometimes', 'Thỉnh thoảng'), ('often', 'Thường xuyên'), ('private', 'Không muốn nói')], max_length=20)),
                ('drinking_status', models.CharField(blank=True, choices=[('never', 'Không'), ('sometimes', 'Thỉnh thoảng'), ('often', 'Thường xuyên'), ('private', 'Không muốn nói')], max_length=20)),
                ('children_status', models.CharField(blank=True, choices=[('none', 'Chưa có'), ('has', 'Đã có'), ('private', 'Không muốn nói')], max_length=20)),
                ('children_plan', models.CharField(blank=True, choices=[('want', 'Muốn có'), ('not_want', 'Không muốn'), ('unsure', 'Chưa quyết định'), ('private', 'Không muốn nói')], max_length=20)),
                ('bio', models.TextField(blank=True, max_length=1500)),
                ('looking_for', models.TextField(blank=True, max_length=1000)),
                ('field_visibility', models.JSONField(blank=True, default=dict)),
                ('visibility_status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Công khai'), ('hidden_by_user', 'Người dùng ẩn'), ('hidden_by_moderator', 'Kiểm duyệt ẩn'), ('suspended', 'Đình chỉ'), ('deleted', 'Đã xóa')], db_index=True, default='draft', max_length=32)),
                ('completion_percent', models.PositiveSmallIntegerField(default=0)),
                ('verification_level', models.CharField(choices=[('none', 'Chưa xác minh'), ('identity_verified', 'Đã xác minh danh tính'), ('recheck_required', 'Cần xác minh lại'), ('revoked', 'Đã thu hồi')], db_index=True, default='none', max_length=32)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='profiles', to='profiles.interest')),
                ('occupation_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profiles.occupationcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('current_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_profiles', to='profiles.province')),
                ('hometown_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hometown_profiles', to='profiles.province')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('public_url', models.URLField(max_length=1000)),
                ('thumbnail_object_key', models.CharField(blank=True, max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('moderation_status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='approved', max_length=16)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
            options={
                'ordering': ('position', 'created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('profile',), name='unique_primary_photo_per_profile')],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['visibility_status', 'gender', 'birth_date'], name='profiles_pr_visibil_420a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['visibility_status', 'current_province'], name='profiles_pr_visibil_55e4af_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['visibility_status', 'hometown_province'], name='profiles_pr_visibil_6de831_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['visibility_status', 'education_level'], name='profiles_pr_visibil_f68216_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['visibility_status', 'income_band'], name='profiles_pr_visibil_4e87c4_idx'),
        ),
    ]
