import Link from "next/link";
import { CheckCircle2, HeartHandshake, LockKeyhole, MessageCircle, Search, ShieldCheck, Video } from "lucide-react";
import { Suspense } from "react";

const principles = [
  [Search, "Khám phá có tiêu chí", "Chọn điều quan trọng với bạn trước khi bắt đầu làm quen."],
  [ShieldCheck, "Xác minh minh bạch", "Tích xanh phản ánh một bước xác minh, không phải lời hứa thay bạn."],
  [HeartHandshake, "Kết nối có đồng thuận", "Lời làm quen được chấp nhận trước khi mở trò chuyện."],
  [LockKeyhole, "Quyền riêng tư dễ hiểu", "Bạn chọn ai có thể xem từng trường thông tin trong hồ sơ."],
  [MessageCircle, "Trò chuyện riêng tư", "Chat 1–1 realtime với quyền chặn và báo cáo."],
  [Video, "Gọi khi cả hai sẵn sàng", "Video call 1–1 chỉ mở trong kết nối phù hợp."],
] as const;

export default function Landing(){return <main className="landing"><header className="landing-nav"><div className="brand">LoveLink</div><div><Link className="btn btn-ghost" href="/auth/login">Đăng nhập</Link><Link className="btn btn-primary" href="/auth/register">Tạo tài khoản</Link></div></header><section className="hero"><div><span className="eyebrow">Hẹn hò an toàn · Kết nối có đồng thuận</span><h1>Tìm một người phù hợp, bằng một hồ sơ đáng tin cậy.</h1><p>LoveLink giúp người độc thân tạo hồ sơ, lọc theo tiêu chí rõ ràng, xin kết nối trước khi trò chuyện và gọi video riêng tư.</p><div className="hero-actions"><Link className="btn btn-primary big" href="/auth/register">Bắt đầu miễn phí</Link><Link className="btn btn-secondary big" href="/auth/login">Tôi đã có tài khoản</Link></div></div><div className="hero-visual" aria-label="Minh họa luồng kết nối LoveLink"><div className="mock-profile p1"><div className="mock-photo">L</div><b>Lan, 26</b><span>Hà Nội · Marketing</span><small><CheckCircle2 size={14}/> Đã xác minh</small></div><div className="mock-profile p2"><div className="mock-photo">M</div><b>Minh, 28</b><span>Hà Nội · Kỹ sư</span><small><CheckCircle2 size={14}/> Đã xác minh</small></div><div className="consent-note"><HeartHandshake size={18}/><span>Hai bên cùng đồng ý<br/><b>Mở cuộc trò chuyện</b></span></div><HeartHandshake className="hero-heart"/></div></section><section className="trust-strip" aria-label="Nguyên tắc LoveLink"><span><ShieldCheck size={18}/> Xác minh trước khi tin</span><span><HeartHandshake size={18}/> Đồng thuận trước khi trò chuyện</span><span><LockKeyhole size={18}/> Kiểm soát quyền riêng tư</span></section><section className="features"><h2>Một luồng rõ ràng, đặt niềm tin đúng chỗ</h2><p className="section-intro">Từ khám phá đến cuộc trò chuyện, mỗi bước giữ lại quyền lựa chọn của bạn.</p><div className="feature-grid">{principles.map(([Icon,title,body])=><article key={title}><Icon/><h3>{title}</h3><p>{body}</p></article>)}</div></section><footer><span>© 2026 LoveLink</span><Link href="/terms">Điều khoản</Link><Link href="/privacy">Quyền riêng tư</Link></footer></main>}
