# Generated by Django 6.0.6 on 2026-08-04 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('submitted', 'Đã gửi'), ('in_review', 'Đang xét duyệt'), ('needs_more_info', 'Cần bổ sung'), ('verified', 'Đã xác minh'), ('rejected', 'Từ chối'), ('expired', 'Hết hạn'), ('revoked', 'Thu hồi')], db_index=True, default='draft', max_length=24)),
                ('challenge_code', models.CharField(max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason_code', models.CharField(blank=True, max_length=64)),
                ('user_visible_reason', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('review_verificationrequest', 'Can review verification requests')],
            },
        ),
        migrations.CreateModel(
            name='VerificationEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('id_front', 'Mặt trước giấy tờ'), ('selfie', 'Ảnh selfie'), ('challenge_selfie', 'Selfie với mã')], max_length=24)),
                ('private_object_key', models.CharField(max_length=500, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='verification.verificationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32)),
                ('previous_status', models.CharField(max_length=24)),
                ('new_status', models.CharField(max_length=24)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='verification.verificationrequest')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['status', 'submitted_at'], name='verificatio_status_b771d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationevidence',
            constraint=models.UniqueConstraint(fields=('request', 'evidence_type'), name='unique_evidence_type_per_request'),
        ),
    ]
