# Generated by Django 6.0.6 on 2026-08-04 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('profile', 'Hồ sơ'), ('message', 'Tin nhắn'), ('call', 'Cuộc gọi'), ('photo', 'Ảnh')], max_length=20)),
                ('target_id', models.CharField(max_length=128)),
                ('reason_code', models.CharField(choices=[('fake', 'Giả mạo'), ('scam', 'Lừa đảo'), ('harassment', 'Quấy rối'), ('sexual', 'Nội dung tình dục'), ('threat', 'Đe dọa'), ('spam', 'Spam'), ('underage', 'Chưa đủ tuổi'), ('wrong_photo', 'Ảnh không chính chủ'), ('other', 'Khác')], max_length=32)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Mới'), ('in_review', 'Đang xử lý'), ('action_taken', 'Đã xử lý'), ('dismissed', 'Bỏ qua'), ('escalated', 'Chuyển cấp')], db_index=True, default='open', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('review_report', 'Can review user reports')],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('warn', 'Cảnh báo'), ('hide_photo', 'Ẩn ảnh'), ('hide_profile', 'Ẩn hồ sơ'), ('suspend', 'Đình chỉ'), ('ban', 'Cấm'), ('revoke_badge', 'Thu hồi tích xanh'), ('restore', 'Khôi phục')], max_length=32)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='moderation.report')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block_pair'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='blocker_not_blocked')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='moderation__status_2a84ce_idx'),
        ),
    ]
