# Generated by Django 6.0.6 on 2026-08-04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneVerificationChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=16)),
                ("code_hash", models.CharField(max_length=128)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                (
                    "request_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_verification_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at",),
            },
        ),
        migrations.AddIndex(
            model_name="phoneverificationchallenge",
            index=models.Index(
                fields=["user", "-sent_at"],
                name="accounts_ph_user_id_99621f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="phoneverificationchallenge",
            index=models.Index(
                fields=["phone", "-sent_at"],
                name="accounts_ph_phone_7f64da_idx",
            ),
        ),
    ]
