"use client";
import {useEffect,useState} from "react";import {api} from "@/lib/api";import type {Profile} from "@/lib/types";import {ProfileCard} from "@/components/profile-card";import {Button,Empty,Field,Input,Select} from "@/components/ui";
type Ref={provinces:{code:string;name:string}[];occupations:{id:string;name:string}[];choices:Record<string,[string,string][]>};
const defaults={min_age:18,max_age:40,min_height:"",max_height:"",province:"",hometown:"",occupation:"",education:"",income:"",goal:"",verified:false,sort:"recommended"};
export default function Discover(){const [items,setItems]=useState<Profile[]>([]);const [ref,setRef]=useState<Ref|null>(null);const [loading,setLoading]=useState(true);const [next,setNext]=useState<string|null>(null);const [filters,setFilters]=useState<any>(defaults);const [filterOpen,setFilterOpen]=useState(false);
 function query(f=filters){const q=new URLSearchParams();Object.entries(f).forEach(([k,v])=>{if(v!==""&&v!==false)q.set(k,String(v))});return q}
 async function load(f=filters,append=false,url?:string){setLoading(true);try{const r=await api<any>(url?url.replace(/^.*\/api\/v1/,""):`/discover?${query(f)}`);setItems(x=>append?[...x,...(r.results||[])]:r.results||r);setNext(r.next||null);if(typeof window!=="undefined"&&!append)history.replaceState(null,"",`/discover?${query(f)}`)}finally{setLoading(false)}}
 useEffect(()=>{api<Ref>("/reference-data").then(setRef);const params=new URLSearchParams(location.search);const restored={...defaults};for(const k of Object.keys(restored)){if(params.has(k))(restored as any)[k]=k==="verified"?params.get(k)==="true":params.get(k)}setFilters(restored);load(restored)},[]);const set=(k:string,v:any)=>setFilters((x:any)=>({...x,[k]:v}));
 const filtersUi=<><h2>Bộ lọc</h2><div className="two"><Field label="Tuổi từ"><Input type="number" min={18} max={99} value={filters.min_age} onChange={e=>set("min_age",e.target.value)}/></Field><Field label="Đến"><Input type="number" min={18} max={99} value={filters.max_age} onChange={e=>set("max_age",e.target.value)}/></Field></div><div className="two"><Field label="Cao từ"><Input type="number" min={120} max={230} value={filters.min_height} onChange={e=>set("min_height",e.target.value)}/></Field><Field label="Đến"><Input type="number" min={120} max={230} value={filters.max_height} onChange={e=>set("max_height",e.target.value)}/></Field></div>{ref&&<><Field label="Nơi ở"><Select value={filters.province} onChange={e=>set("province",e.target.value)}><option value="">Tất cả</option>{ref.provinces.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</Select></Field><Field label="Quê quán"><Select value={filters.hometown} onChange={e=>set("hometown",e.target.value)}><option value="">Tất cả</option>{ref.provinces.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</Select></Field><Field label="Nghề nghiệp"><Select value={filters.occupation} onChange={e=>set("occupation",e.target.value)}><option value="">Tất cả</option>{ref.occupations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field label="Học vấn"><Select value={filters.education} onChange={e=>set("education",e.target.value)}><option value="">Tất cả</option>{ref.choices.education.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</Select></Field><Field label="Thu nhập"><Select value={filters.income} onChange={e=>set("income",e.target.value)}><option value="">Tất cả</option>{ref.choices.income.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</Select></Field><Field label="Mục tiêu"><Select value={filters.goal} onChange={e=>set("goal",e.target.value)}><option value="">Tất cả</option>{ref.choices.goals.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</Select></Field></>}<label className="check"><input type="checkbox" checked={filters.verified} onChange={e=>set("verified",e.target.checked)}/> Chỉ hồ sơ tích xanh</label><Button className="full" onClick={()=>{load();setFilterOpen(false)}}>Áp dụng</Button><Button variant="ghost" className="full" onClick={()=>{setFilters(defaults);load(defaults);setFilterOpen(false)}}>Xóa bộ lọc</Button></>;
 return <div className="page wide"><div className="page-heading"><div><span className="eyebrow">Khám phá</span><h1>Tìm người phù hợp</h1></div><div className="discover-heading-actions"><Button className="mobile-filter" variant="secondary" onClick={()=>setFilterOpen(true)}>Bộ lọc</Button><Select value={filters.sort} onChange={e=>{const f={...filters,sort:e.target.value};setFilters(f);load(f)}}><option value="recommended">Phù hợp nhất</option><option value="recent">Mới hoạt động</option><option value="newest">Hồ sơ mới</option><option value="age_asc">Tuổi tăng dần</option></Select></div></div><div className="discover-layout"><aside className="filter-panel">{filtersUi}</aside><section>{loading&&!items.length?<div className="empty">Đang tải hồ sơ…</div>:items.length?<><div className="profile-grid">{items.map(p=><ProfileCard key={p.public_id} profile={p}/>)}</div>{next&&<div className="load-more"><Button disabled={loading} variant="secondary" onClick={()=>load(filters,true,next)}>{loading?"Đang tải…":"Xem thêm"}</Button></div>}</>:<Empty title="Chưa tìm thấy hồ sơ" body="Hãy thử nới lỏng một vài điều kiện lọc."/>}</section></div>{filterOpen&&<div className="modal-backdrop mobile-filter-modal"><aside className="filter-panel"><Button variant="ghost" onClick={()=>setFilterOpen(false)}>Đóng</Button>{filtersUi}</aside></div>}</div>}
