# Generated by Django 6.0.6 on 2026-08-04 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair_key', models.CharField(db_index=True, max_length=73)),
                ('intro_message', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Chờ phản hồi'), ('accepted', 'Đã kết nối'), ('declined', 'Đã từ chối'), ('cancelled', 'Đã hủy'), ('expired', 'Hết hạn'), ('blocked', 'Đã chặn')], db_index=True, default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connection_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connection_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sent_at',),
                'indexes': [models.Index(fields=['receiver', 'status', '-sent_at'], name='connections_receive_afafe8_idx'), models.Index(fields=['sender', 'status', '-sent_at'], name='connections_sender__fdf92b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='connection_sender_not_receiver'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('pair_key',), name='unique_pending_connection_pair')],
            },
        ),
    ]
