# Generated by Django 6.0.6 on 2026-08-04 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=160, unique=True)),
                ('call_type', models.CharField(default='video', max_length=12)),
                ('status', models.CharField(choices=[('created', 'Đã tạo'), ('ringing', 'Đang đổ chuông'), ('accepted', 'Đã nhận'), ('connecting', 'Đang kết nối'), ('active', 'Đang gọi'), ('declined', 'Từ chối'), ('cancelled', 'Đã hủy'), ('missed', 'Cuộc gọi nhỡ'), ('ended', 'Đã kết thúc'), ('failed', 'Lỗi')], db_index=True, default='created', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ringing_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=100)),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='messaging.conversation')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['caller', 'status'], name='calls_calls_caller__af597c_idx'), models.Index(fields=['callee', 'status'], name='calls_calls_callee__07f96e_idx')],
            },
        ),
    ]
